### ISSUE TITLE
Some characters are replaced with \f and \b

### ISSUE THREAD

**Issue by rplc** [smalot/pdfparser#124] opened 2016-10-29 14:06 UTC
Hello,

Great libary. Works in most cases like a charm.
But sometimes there is a problem... Currently I've got a problem that occurs in some pdfs (not all!).

The pdf seems to be ok but the parser replaces some characters in the pdf with \f and \b.
I use the parser in a standard/simple way, see the function call below.

```
$parser = new \Smalot\PdfParser\Parser();
$pdf = $parser->parseFile("test.pdf");
file_put_contents("tmp.txt", $pdf->getText());
```

Here are two files. The source pdf and the txt file containing the whole pdf content (including the strange replacements).
[test.pdf](https://github.com/smalot/pdfparser/files/559955/test.pdf)
[tmp.txt](https://github.com/smalot/pdfparser/files/559957/tmp.txt)

Would be great if somebody could help me.

Greetings Alex

**Comment by rplc** [comment] 2016-11-02 12:14
I've tracked the problem down to the Method translateChar in the Font.php Class.
But I still have no clue what causes the problem...

**Comment by aariza-argentina** [comment] 2018-09-05 18:25
I have the same problem, but I detect that the problem is only on the First Page, apparentrly for the page 0 translateChar is not used to translate.

**Comment by Connum** [comment] 2020-09-29 17:51
I went back in time using the provided PDF and can confirm that this issue was fixed with 4f4fd108270c32c0e81ea3dceaac2249162f27dc

**Comment by adrianbj** [comment] 2021-01-27 00:38
This fix works great, but it's not in Font.php in the version I installed via composer. Is that still expected, or should it be in there by now?

**Comment by k00ni** [comment] 2021-01-27 08:36
We had to revert that fix, because it caused problems. 

Reference: https://github.com/smalot/pdfparser/commit/1862686d21b6fb394f9521b5eb651750b64292b9#diff-27bc594b24bd5e2779e8d81ee79810d0ffda03f200f0d53be007a44a9d2cb2de

**Comment by Connum** [comment] 2021-01-27 10:38
We could add `\b` to the replacements list (actually, I thought I had when reverting the fix, but obviously I only added `\f`), but we'd have to check that this doesn't break anything else of course.

**Comment by Connum** [comment] 2021-01-27 11:56
I tested this and it's not enough to just add `\b` to the replacements... (The letter that's supposed to be inits place is still missing) Apparently, `stripcslashes()` does something else to the input that results in the "\b" vanishing from the output while preserving the actual letter. But I don't think I'll find any more time to look into this.

**Comment by adrianbj** [comment] 2021-01-27 14:40
Thanks for explaining - I don't think I am seeing any issues using `stripcslashes()` here, so will stick with that for the moment. You can use this PDF for testing. It would definitely be great to have a better solution for this. I took a look at some other PDF2TXT libraries (including the one I have used in the past) and they do mostly seem to use a character replacement approach for this, rather than `stripcslashes()`, but they are structured so differently that I didn't see an easy way to bring their solutions into this library.

[healthy-chesapeake-waterways.pdf](https://github.com/smalot/pdfparser/files/5880906/healthy-chesapeake-waterways.pdf)

**Comment by GreyWyvern** [comment] 2023-07-21 13:37
Both example PDFs `getText()` text nicely, without any \b or \f with #597

**Closed** 2023-07-26 14:44 UTC
Labels: bug
