### ISSUE TITLE
Form field modification issue - Parser ignores field changes

### ISSUE THREAD

**Issue by MadMat1** [smalot/pdfparser#379] opened 2020-12-26 22:07 UTC
Hi everyone,
I've been testing the parser and I've found an issue within a form (acroform) if you modify a field value previously filled. For some reason acrobat saves internally the previous field value and the parser doesn't notice the new value, in fact it ignores the new created object (new field value = new object)

I've made an example and uploaded [here](https://gofile.io/d/bUTVsz) ([backup](https://github.com/smalot/pdfparser/files/5746462/test.pdf))
First the field value it was "Monday" but then I closed the file, open again and changed the value to "Tuesday", you can see that if you open the file normally, but if you parse it the only object containing the field value is "Monday".

Hope you can help me.
Thanks in advance.

---
**EDIT by @k00ni**: uploaded file to github to have backup.

**Comment by MadMat1** [comment] 2020-12-27 00:37
OK, this is related to pdf incremental updates, and the way a pdf object is added when an update happens.
Is pdfparser ready to incremental updates? My tests suggests not.

**Comment by rubenvanerk** [comment] 2022-01-19 14:35
Duplicate of #43

**Closed** 2022-01-20 06:43 UTC
Labels: question, parsing fail
