### ISSUE TITLE
pdf with attachments

### ISSUE THREAD

**Issue by mgrootbramel85** [smalot/pdfparser#274] opened 2020-03-03 13:31 UTC
Hello,

I have a pdf file with attachments (xml file), is it possible to find this xml and save this to a directory?

![2020-03-03_14-30-33](https://user-images.githubusercontent.com/61742500/75780422-9c112d80-5d5b-11ea-9c0f-8ba8402fdd08.png)

**Comment by rubenvanerk** [comment] 2020-06-05 05:56
Duplicate of #188

**Closed** 2020-06-05 06:30 UTC
Labels: question
