### ISSUE TITLE
How can i get form fields value?

### ISSUE THREAD

**Issue by crocodile305** [smalot/pdfparser#370] opened 2020-11-19 01:23 UTC
I would like to get form fields value but i can't get.

        $parser = new \Smalot\PdfParser\Parser();
        $pdf = $parser->parseFile("GENERIC%20FORM%20FOR%20SETUP.pdf");
        $text = $pdf->getText();
        echo $text;

and the result like this:
GENERIC FORM FOR SETUP First Name __________________ Last Name __________________ Address __________________ Address 2 __________________
[GENERIC_FORM_FOR_SETUP.pdf](https://github.com/smalot/pdfparser/files/5563715/GENERIC_FORM_FOR_SETUP.pdf)
If someone know how to fix this problem.please help me.
Thanks a lot.

**Comment by med-ezzairi** [comment] 2020-12-05 12:44
I tried to find a way to get form values but no result, instead you could use, pdftk as referenced in this post: https://stackoverflow.com/a/32726267
and then, search for the FieldValue property in the output text file (there will be all fields)

**Comment by rubenvanerk** [comment] 2022-01-19 14:35
Duplicate of #43

**Closed** 2022-01-20 06:44 UTC
Labels: question
