### ISSUE TITLE
PDFParser Missing catalog Error in Demo and using composer also

### ISSUE THREAD

**Issue by prestashoppay** [smalot/pdfparser#177] opened 2017-11-21 07:31 UTC
Hi Team,

Subject : Missing catalog
We are using the PDFParser using composer.
When we tested with your demo link and uploaded the pdf file its showing the "Missing Catalog" Error.
Could you please let m know what is the issues in pdf file ?

Thanks

**Comment by tim-peterson** [comment] 2018-01-09 17:47
See this thread and possible solution for you: https://github.com/smalot/pdfparser/issues/32#issuecomment-356353448

**Comment by DylanHobbs** [comment] 2018-10-07 18:13
I'm very late to this party, but for anyone searching later on: For me the issue was pdf versions.
It doesn't like 1.7 at the very least. Converting the pdf's to 1.4 worked. 
Here is a php library for that if needed: https://github.com/xthiago/pdf-version-converter

**Comment by rubenvanerk** [comment] 2020-06-04 19:20
Duplicate of #32

**Closed** 2020-06-04 20:32 UTC
