### ISSUE TITLE
Space issues in parsing text

### ISSUE THREAD

**Issue by bhaveshsurani** [smalot/pdfparser#314] opened 2020-06-26 13:20 UTC
Hello Team

Facing issues with parsing PDF to text....as its add single space at some words.... Do we have any solutions

![image](https://user-images.githubusercontent.com/1414787/85861381-e2dcd480-b7dd-11ea-8167-605d6c4a28e2.png)

**Comment by bhaveshsurani** [comment] 2020-06-26 13:34
[21 Club New York Feb 17 NB-21 Club Summary.pdf](https://github.com/smalot/pdfparser/files/4837193/21.Club.New.York.Feb.17.NB-21.Club.Summary.pdf)
Here attached file for more details... i have parsed this file with demo and facing this issue as given in screenshot

**Comment by rubenvanerk** [comment] 2020-06-26 14:18
This is a duplicate of #72

I suggest to try this: https://github.com/smalot/pdfparser/issues/72#issuecomment-256330244

For now you'll have to edit the source code. There's an issue discussing modifying the parser's behavior like this: https://github.com/smalot/pdfparser/issues/305

**Closed** 2020-07-02 13:14 UTC
Labels: duplicate, missing or incomplete functionality
