### ISSUE TITLE
Does not parse text from pdf file

### ISSUE THREAD

**Issue by mapexpert** [smalot/pdfparser#564] opened 2022-11-30 14:07 UTC
```
$content = Storage::get('iaa/receipt1.pdf');
$parser = new \Smalot\PdfParser\Parser;
$data = $parser->parseContent($content);
dd($data->getText());
```
Output:
b"%\t\n\x00X\x00\\x00H\x00U\x00\x03\x005\x00H\x00F\x00H\x00L\x00S\x00W\t\n\x005\t\n\n\x00H\x00F\x00H\x00L\x00S\x00W\x00\x03\x00\x06\t\n\x00\x14\t\n \x00\x1C\x00\x19\x00\x17\x00\x1A\x00\x19\x00\x17\x00\x13\t\n\x005\t\n\n\x00H\x00F\x00H\x00L\x00S\x00W\x00\x03\x00'\x00D\x00W\x00H\t\n\x00\x14\t\n \x00\x14\x00\x12\x00\x15\x00\x16\x00\x12\x00\x15\x00\x13\x00\x15\x00\x15\t\n\x005\t\n\n\x00H\x00F\x00H\x00L\x00Y\x00H\x00G\x00\x03\x00%\x00\\t\n\x00$\t\n \x006\x00$\x003\x00\x03\x006\t\n\x006\t\n\n\x00R\x00O\x00G\x00\x03\x00$\x00W\x00\x03\x00%\x00U\x00D\x00Q\x00F\x00K\t\n\x00\x19\t\n 

[receipt1.pdf](https://github.com/smalot/pdfparser/files/10123883/receipt1.pdf)
IMHO parser does not parse font correctly and does not load translate tables.

**Comment by Uplink03** [comment] 2023-01-18 03:41
I've been having a similar problem with a PDF, but it turns out it's different from yours, @mapexpert . The problem in your case is how `Font::loadTranslateTable` wants to figure out the Unicode table, and it ends up with an empty table. Because of that, the `Font::decodeContentByToUnicodeCMapOrDescendantFonts` also fails. Not that it guarantees that it will work, as it has this comment: `@todo Seems this is invalid algorithm that do not follow pdf-format specification. Must be rewritten.`

My similar problem was a lot easier to fix, as it was caused by `Encoding::init`. If I replace this:

```php
if ($this->has('BaseEncoding') {
    $this->encoding = EncodingLocator::getEncoding($this->getEncodingClass())->getTranslations();

    // the code that loads Differences
}
```

with

```php
if ($this->has('BaseEncoding') {
    $this->encoding = EncodingLocator::getEncoding($this->getEncodingClass())->getTranslations();
}

// the code that loads Differences
```

which is basically to take `// the code that loads Differences` out of the big `if` block, then my problem is fixed.
 
I'm not capable enough at the moment to understand how to fix the problem you're having though.

I gave your PDF to `pdf2txt.py` (from the `pdfminer` Python project) and to `pdftotext` (from the `poppler-utils` package on Ubuntu 22.04), and they both barfed at it, while both decoded my own PDF's text just fine.

I'm writing this hoping it will give someone a hint of where to look when they make an attempt to fix this.

**Comment by NazarSolovei** [comment] 2023-04-02 18:32
@mapexpert, have you solved the issue?

**Comment by mapexpert** [comment] 2023-07-09 09:00
> @mapexpert, have you solved the issue?

no. I did not. still have the issue

**Comment by k00ni** [comment] 2023-07-10 06:51
@mapexpert can you try the suggestion of @Uplink03 and get back to us, if this works: https://github.com/smalot/pdfparser/issues/564#issuecomment-1386440468

**Comment by mapexpert** [comment] 2023-07-10 07:26
> 

I tried @Uplink03 suggestion and it does not work in my case

**Comment by GreyWyvern** [comment] 2023-07-10 13:28
Definitely something weird going on here with fonts. If I save the file as a reduced size PDF in Acrobat the text issue remains. If I select all the text in the PDF in Adobe Acrobat, convert the font to Arial, then save the file, PdfParser parses the text properly.

**Comment by GreyWyvern** [comment] 2023-08-10 18:14
This appears to be fixed in the latest release v2.7.0. Although a lot of spacing issues remain, the text is extracted successfully.

**Comment by ephrin** [comment] 2023-09-08 09:40
@GreyWyvern close this then?

**Comment by mapexpert** [comment] 2023-09-08 09:43
> @GreyWyvern @mapexpert close this then?

Yes

**Closed** 2023-09-11 06:02 UTC
Labels: bug
