### ISSUE TITLE
Undefined offset: 97 in Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091

### ISSUE THREAD

**Issue by cachak** [smalot/pdfparser#360] opened 2020-10-23 23:56 UTC
code :
```php
<?php
 
// Include Composer autoloader if not already done.
include 'vendor/autoload.php';
 
// Parse pdf file and build necessary objects.
$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile('data.pdf');
 
// Retrieve all pages from the pdf file.
$pages  = $pdf->getPages();
 
// Loop over each page to extract text.
foreach ($pages as $page) {
    echo $page->getText();
}
```
i m try data.pdf, i try data in [demo](https://www.pdfparser.org/demo) success

errors :
```bash
riptGlyphs.php on line 1091
PHP Notice:  Undefined offset: 53 in /project/php-pdf/vendor/smalot/pdfparser/src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091
PHP Notice:  Undefined offset: 32 in /project/php-pdf/vendor/smalot/pdfparser/src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091
PHP Notice:  Undefined offset: 32 in /project/php-pdf/vendor/smalot/pdfparser/src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091
PHP Notice:  Undefined offset: 32 in /project/php-pdf/vendor/smalot/pdfparser/src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091
PHP Notice:  Undefined offset: 32 in /project/php-pdf/vendor/smalot/pdfparser/src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091
PHP Notice:  Undefined offset: 80 in /project/php-pdf/vendor/smalot/pdfparser/src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091
PHP Notice:  Undefined offset: 97 in /project/php-pdf/vendor/smalot/pdfparser/src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091
PHP Notice:  Undefined offset: 115 in /project/php-pdf/vendor/smalot/pdfparser/src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091
PHP Notice:  Undefined offset: 105 in /project/php-pdf/vendor/smalot/pdfparser/src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091
PHP Notice:  Undefined offset: 101 in /project/php-pdf/vendor/smalot/pdfparser/src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091
PHP Notice:  Undefined offset: 32 in /project/php-pdf/vendor/smalot/pdfparser/src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091
PHP Notice:  Undefined offset: 83 in /project/php-pdf/vendor/smalot/pdfparser/src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php on line 1091

```

**Comment by k00ni** [comment] 2020-10-24 13:41
Thank you for reporting. We have a duplicate of #359, which reports the same notices.

I will close this issue in favor of #359, so we can focus our attention there.

**Closed by k00ni** 2020-10-24 13:41 UTC
