### ISSUE TITLE
Undefined Offset in Parser.php causing FollowUp Fatal Error

### ISSUE THREAD

**Issue by kaystrobach** [smalot/pdfparser#19] opened 2014-02-15 12:21 UTC
```
PHP Notice:  Undefined offset: 1 in smalot/pdfparser/src/Smalot/PdfParser/Parser.php on line 178
PHP Warning:  substr() expects parameter 2 to be long, string given in smalot/pdfparser/src/Smalot/PdfParser/Parser.php on line 190
PHP Fatal error:  Call to undefined method Smalot\PdfParser\Object::decodeText() in smalot/pdfparser/src/Smalot/PdfParser/Object.php on line 306
```

http://stackoverflow.com/questions/7116995/is-it-possible-in-php-to-prevent-fatal-error-call-to-undefined-function

**Comment by Connum** [comment] 2020-09-26 12:59
> 
> 
> The same problem with: http://arxiv.org/pdf/1312.6082v4

That PDF seems to cause some other issues as well... The  text is broken up and parts of it are missing. But I'd suggest we concentrate on the issue at hand and you open up another issue for the remaining parsing errors!

This issue should be fixed with #345!

**Comment by Connum** [comment] 2020-09-30 16:17
> 
> 
> The same problem with: http://arxiv.org/pdf/1312.6082v4

Quick update: The remaining issues in that PDF will be fixed with #349. We can't use that probably copyrighted PDF file for unit testing, but I was able to confirm locally that it's fixed.

**Comment by PetrToman** [comment] 2020-09-30 19:38
Cool!

**Comment by k00ni** [comment] 2020-10-01 07:04
In my opinion it doesn't matter whether the PDF file works or not. Errors like:

> PHP Notice:  Undefined offset: 1 in smalot/pdfparser/src/Smalot/PdfParser/Parser.php on line 178
> PHP Warning:  substr() expects parameter 2 to be long, string given in smalot/pdfparser/src/Smalot/PdfParser/Parser.php on line 190
> PHP Fatal error:  Call to undefined method Smalot\PdfParser\Object::decodeText() in smalot/pdfparser/src/Smalot/PdfParser/Object.php on line 306

can't happen and they point to faulty code.

@Connum can you tell me if they are fixed? Parsing errors should be handled in a separate issue, yes.

**Comment by Connum** [comment] 2020-10-01 07:18
We could throw an Exception when there is only one value where we expect two.

**Comment by k00ni** [comment] 2020-10-01 07:31
> We could throw an Exception when there is only one value where we expect two.

What do you mean? I meant, if that errors can't happen again, because there are precautions for instance.

**Comment by Connum** [comment] 2020-10-01 08:57
_Sometimes it feels like two Germans lost in translation... 😅_

This error was caused by splitting a string for a space and expecting two numeric values. However, the string may contain a line break after the space instead of the expected value, so the second value was an empty string, which was passed to `substr()`. We could cast the value to an int as an extra precaution?

**Comment by k00ni** [comment] 2020-10-01 11:26
Yeah, maybe :smile:

In this issue multiple problems are handled at the same time. So to make things easier I wanted to focus on the PHP errors and not the parsing errors first. After that we should make a new issue for each parsing error. Hope that makes more sense.

**Closed** 2020-10-06 08:08 UTC
Labels: bug

**Comment by ericksho** [comment] 2022-04-29 19:25
Hi, I have the same issue with this file: https://drive.google.com/file/d/10cV9empimt-qH5FPF0e3xYGjJ7R7iC-X/view?usp=sharing

with this code:
```
$parser = new PDFParser();
  $documentPath = $this->folder.'document_'.$document->getId().'.pdf';
  $pdf = $parser->parseFile($documentPath);

  $pages = $pdf->getPages();
  $page = $pages[0];
  $dataTm = $page->getDataTm();
```

the last line throws the `Notice: Undefined offset: 28 `
