### ISSUE TITLE
I can extract text, but cannot extract form field data

### ISSUE THREAD

**Issue by MajorLeeGassole** [smalot/pdfparser#135] opened 2016-12-09 12:14 UTC
I created a simple pdf using InDesign and can extract the text from my pdf using smalot/pdfparser code. The content within the pdf form fields does not get extracted though. Would parseContent or getContent work? If so, how is that configured? I have tried numerous ways and have gone through the API documentation, but I can't make sense of it.

```php
include('pdfparser/vendor/autoload.php');
$parser = new \Smalot\Pdfparser\Parser();
$pdf = parser->parseFile('simple.pdf');
$text = $pdf->getText();
echo $text;
```

I've successfully used getDetails, but can't figure out parseContent or getContent - if they are even the correct solution for extracting the form field data that was entered and saved.
[simple.pdf](https://github.com/smalot/pdfparser/files/642097/simple.pdf)

**Comment by rubenvanerk** [comment] 2022-01-19 14:35
Duplicate of #43

**Closed** 2022-01-20 06:55 UTC
