### ISSUE TITLE
Invalid object reference for $obj.

### ISSUE THREAD

**Issue by mschrading** [smalot/pdfparser#649] opened 2023-11-05 12:52 UTC
smalot/pdfparser (v2.7.0)
 - PHP Version: 7.4
 - PDFParser Version: v2.7.0 

### Description

I am writing to you today because I have a problem with your pdfParser on the live server. I get an exception:
"Invalid object reference for $obj." in getIndirectObject
on line 521:

```
protected function getIndirectObject(string $pdfData, array $xref, string $objRef, int $offset = 0, bool $decoding = true): array
     {
         /*
          * build indirect object header
          */
         // $objHeader = "[object number] [generation number] obj"
         $objRefArr = explode('_', $objRef);
         if (2 !== count($objRefArr)) {
             throw new \Exception('Invalid object reference for $obj.');
         }
```

I'm using cakephp 4.4

How can I avoid this? Better is not to parse this pdf and maybe get an error list and return an empty array, or something?

Can you please help me?

Parsing will always run in an exception on RawDataParser.php in methode getIndirectObject

```
if (2 !== \count($objRefArr)) {
    throw new \Exception('Invalid object reference for $obj.');
}
```

### Expected output & actual output

exception Invalid object reference for $obj.

**Comment by k00ni** [comment] 2023-11-06 07:24
Duplicate of #550. Further notes there.

**Closed by k00ni** 2023-11-06 07:24 UTC
