### ISSUE TITLE
Wrong characters parsed with getText()

### ISSUE THREAD

**Issue by OneSoftIO** [smalot/pdfparser#260] opened 2019-10-10 23:35 UTC
I have a code:

`$parser = new Parser();`
`$pdf = $parser->parseFile(storage_path($file->full_path));`

It's a simple code to parse file content, after doing ->getText() output is:

> 1\t\fü\x00\x03\x00\x1C\x00\x18\x00\x0F\x00\x16\x007\t0\x00\b\x00 \t\fü\x00\x03\x00\x1C\x00\x18\x00\x0F\x00\x16\x007\t\fü\x00\x03\x00\x1C\x00\x18\x00\x0F\x00\x16\x007\t\n
> Costi di spedizione\t\fü\x00\x03\x00\x14\x00\x17\x00\x0F\x00\x1C\x009\t\fü\x00\x03\x00\x14\x00\x17\x00\x0F\x00\x1C\x009\t\fü\x00\x03\x00\x14\x00\x17\x00\x0F\x00\x1C\x009
> 

Bus some part of pdf is being read normally. 

Can you, please, help?

**Comment by machekhin** [comment] 2020-01-11 10:17
I`ve make a little fix here:
https://github.com/smalot/pdfparser/pull/269

You can change this file in your project while this pull request will be merged

**Comment by Connum** [comment] 2020-09-22 13:11
@OneSoftIO / @machekhin could you please provide a test file to reproduce this with? Because the fix for this breaks other PDF parsing processes and resulted in at least three new issues so far...

**Comment by machekhin** [comment] 2020-09-22 13:29
@Connum , sorry, I can`t show You this file even I find it, 'cause it`s a commercial document.
Anyway, it was a trouble with parse 'tab'-char \t. The previouse version had manual replace method and some special chars (like \f or \t) broke parcing.

**Comment by Connum** [comment] 2020-09-22 13:52
That's unfortunate... I'm still unsuccessful in trying to produce a PDF with a tab or form feed character that will crash or fail with pdfparser prior to the fix...

**Comment by machekhin** [comment] 2020-09-22 13:56
Maybe it was really \f. It is absent in the previous version:

https://github.com/smalot/pdfparser/pull/269/commits/4f4fd108270c32c0e81ea3dceaac2249162f27dc

**Comment by Connum** [comment] 2020-09-22 13:59
> 
> 
> Maybe it was really \f. It is absent in the previous version:
> 
> [4f4fd10](https://github.com/smalot/pdfparser/commit/4f4fd108270c32c0e81ea3dceaac2249162f27dc)

Yeah, probably, as `\t` was already present in the replacement code before.
I think the issue might be that `stripcslashes()` converts some but not all of the cases that the previous "manual" replacement did, therefore causing the issues with PDFs that worked fine before. So a combination of both could be the key to success. But we'll definitely need a PDF that shows the error when used with a version before the fix to get to the bottom of this...

I also fear that `stripcslashes()` might erroneously try to convert some cases that are not normally escaped in PDFs, but I'd need to find out more details about what that function does escape. The [docs](https://www.php.net/manual/en/function.stripcslashes.php) simply state
>"Recognizes C-like \n, \r ..., octal and hexadecimal representation.
If that would indeed be the case, it could do more harm than it helps keeping the code simpler...

**Comment by Connum** [comment] 2020-09-22 14:01
@machekhin If you do find the time and the PDF that failed, could you test if it is parsed fine when adding `\f` to the manual replacement code instead of using `stripcslashes()`?

```php
            $text = str_replace(
                array('\\\\', '\(', '\)', '\n', '\r', '\t', '\f', '\ '),
                array('\\', '(', ')', "\n", "\r", "\t", "\f", ' '),
                $text
            );
```

That way, we could make sure that this issue can be closed again while resolving the other three issues as well.

**Comment by k00ni** [comment] 2020-09-22 14:43
> That way, we could make sure that this issue can be closed again while resolving the other three issues as well.

Can you list these issues here please (again)? Thanks.

**Comment by machekhin** [comment] 2020-09-22 14:44
@Connum Our team found that PDF and I've checked your new code. It's alright.

**Comment by Connum** [comment] 2020-09-22 17:10
Perfect, thanks! Yes, those were the issues!
I'll make the fix, add some tests and prepare the PR!

**Closed** 2020-09-30 07:40 UTC
Labels: bug
