### ISSUE TITLE
Missing catalog.

### ISSUE THREAD

**Issue by sinan8655** [smalot/pdfparser#173] opened 2017-10-25 04:07 UTC
Hello,

When i try to parse the pdf file, i can see the warning 'Missing Catalog'.
Could you please tell me the meaning of it?
Also please tell me if this sdk can fix it.

Regards,
Sinan

**Comment by johnrobertporter** [comment] 2017-11-15 17:23
I come across this error too.

It happens in my case when we try to parse a PDF that was printed to PDF from Microsoft Word on Windows.

**Comment by tim-peterson** [comment] 2018-01-09 17:45
I might address your issue on this other thread: https://github.com/smalot/pdfparser/issues/32#issuecomment-356353448

**Comment by rubenvanerk** [comment] 2020-06-04 19:21
Duplicate of #32

**Closed** 2020-06-04 20:32 UTC
