### ISSUE TITLE
Exception: Missing catalog

### ISSUE THREAD

**Issue by StudPro** [smalot/pdfparser#272] opened 2020-02-13 11:21 UTC
Hi,
i tried to parse a pdf born from "word openoffice" but return an exception with a "Missing catalog". If hide error the process return a empty string. 

I use the last version from composer

File
pdfparser/src/Smalot/PdfParser/Document.php 248

Solution?

Thank's a lot

**Comment by styler2go** [comment] 2020-05-08 21:34
Also got this problem. Any ideas?

**Comment by j0k3r** [comment] 2020-05-25 19:11
Could you provide a PDF sample to reproduce the bug?

**Comment by rubenvanerk** [comment] 2020-06-04 19:20
Duplicate of #32

**Closed** 2020-06-04 20:32 UTC
Labels: missing or incomplete functionality, needs more info
