### ISSUE TITLE
Problem to parse some PDF

### ISSUE THREAD

**Issue by hectnandez** [smalot/pdfparser#98] opened 2016-03-16 08:59 UTC
Hi, first, you have a really good work with this library, so congrats.

Now, I been trying to parse this file https://drive.google.com/open?id=0BzR_159DYIY8VEtZd1Q0enBaM28 and I getting nothing, looking for similary issue's I found in this #7  but this issue was in 2014 and is the same problem for me, even I have the same problem with this document https://www.avira.com/documents/products/pdf/en/man_avira_rescue_system_en.pdf when I try to parse.

this is the code what i applied:

```php
use Smalot\PdfParser\Parser;
$parser = new Parser();
$pdf = $parser->parseFile(PDFFILE);
$pages = $pdf->getPages();
foreach ($pages as $page){
     $page->getText();
}
```

Making a debug to your library the problem begins in the parserFile function, but I can't go trough this. I use the v0.9.25.

I really apreciate your help. cheers!!!.

**Comment by hectnandez** [comment] 2016-03-16 09:38
this is a little proyect to demostrated the issue.


[pruebas.zip](https://github.com/smalot/pdfparser/files/175624/pruebas.zip)

**Comment by Connum** [comment] 2020-09-28 18:56
The first file from Google Drive is no longer available, but I tried the second linked PDF file, which is getting parsed (some spacing issues, but otherwise fine). I didn't have

**Comment by k00ni** [comment] 2020-09-29 07:15
> The first file from Google Drive is no longer available, but I tried the second linked PDF file, which is getting parsed (some spacing issues, but otherwise fine). I didn't have

What do you wanted to say?

**Comment by Connum** [comment] 2020-09-29 07:19
Whoops, that got cut off somehow...
I didn't have the time to fully dive into the provided sample project. but as far as I could see, it only parses page by page using `getText()`, the same as my local test script does as well.

**Comment by k00ni** [comment] 2020-09-29 11:48
> it only parses page by page using getText(), the same as my local test script does as well.
... so, this is fine? Or is there a problem still?

**Comment by Connum** [comment] 2020-09-29 15:17
From my point of view, at least for the second file that we're still able to test, this should be regarded as fixed. The text is parsed instead of an empty result being returned.

**Comment by k00ni** [comment] 2020-09-30 07:48
@hectnandez if you can please provide us another PDF which causes the problems you talked about (PDF must be free to use and will be part of our test environment). I will keep that issue open, but may closed it because we can't reproduce the problem.

**Closed** 2024-07-18 05:53 UTC
Labels: needs more info, parsing fail
